### ISSUE TITLE
[Question] Purge expired tokens from store

### ISSUE THREAD

**Issue by okonon** [layerhq/express-jwt-blacklist#4]
Hello @ppcat @yaacovCR @nilgradisnik Thanks for such a great plugin.
I have a quick question. Is there a way to remove exited token from the store? I am using Redis for persistence.

Thanks

**Comment by yaacovCR** [comment]
Removing a token from the store would have the effect, I believe, of reversing its blacklisting, ie unrevoking it. Is that what you would be trying to accomplish?

If you just want to make sure the store stays small in size, the library takes care of this automatically if you set the exp claim in your token, as there is no need to explicitly blacklist expired tokens. You can also pass a lifetime parameter to the revoke function to temporarily revoke a token from the get-go, presumably for the same reason.

An explicit unrevoke method could be added to the library, but I imagine @nilgradisnik would want to know your use case first, what you are trying to accomplish...

**Comment by okonon** [comment]
@yaacovCR thanks for your response. What i was missing is that the library automatically calculates ttl based on exp. I can see it in the docs now.
Thanks!
